services:

  php-fpm:
    environment:
      - PHP_OPCACHE_ENABLE=${PHP_OPCACHE:-0}

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: local/Dockerfile
    depends_on:
      - nginx-base
    ports:
      - "8080:443"

  redis:
    ports:
      - "127.0.0.1:63791:6379"

  sql:
    ports:
      - "54321:5432"
